// Which column defaults PostgreSQL has and SQL Server does not.
//
//   node tools/default-audit.mjs
//
// The EF model was scaffolded from PostgreSQL once, and scaffolding records a
// column's type and nullability but not always the default behind it. That did
// not matter for as long as the schema was being read INTO the model — the
// defaults really were there. It matters now that a schema is GENERATED from
// it: a NOT NULL column whose default did not come across is a 500 on every
// INSERT that does not name it, and the INSERTs in this application name the
// columns they care about and leave the rest to the database.
//
// Registration was the first one found, by running it. This exists so the rest
// are found by reading rather than by a customer.
//
// The comparison is Prisma's schema against SQL Server's catalogue, because
// Prisma's schema IS the PostgreSQL one — see the note in README about which
// repository owns which.

import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const PRISMA = process.env.PRISMA_SCHEMA
  ?? 'C:/Users/Aio/autoparts-hub/autoparts-hub/prisma/schema.prisma';

const SQLCMD = process.env.SQLCMD
  ?? 'C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/sqlcmd.exe';

const SERVER = process.env.TEST_SQLSERVER_SERVER ?? '(localdb)\\MSSQLLocalDB';
const DATABASE = process.env.TEST_SQLSERVER_DATABASE ?? 'AutoPartsHub';

/**
 * Defaults Prisma applies in the application rather than in the database.
 *
 * `cuid()` and `uuid()` are generated by the client before the row is sent, so
 * PostgreSQL has no default for them either and neither should SQL Server.
 * Listing them is the difference between "the two agree" and "both are
 * missing it".
 */
const APPLICATION_SIDE = /^(cuid|uuid|auto|autoincrement|dbgenerated)\(/;

/** Every field carrying a database default, as model -> field -> the default. */
function prismaDefaults(source) {
  const found = [];
  let model = null;

  for (const line of source.split(/\r?\n/)) {
    const opening = line.match(/^\s*model\s+(\w+)\s*\{/);
    if (opening) { model = opening[1]; continue; }
    if (model && /^\s*\}/.test(line)) { model = null; continue; }
    if (!model) continue;

    // Comments can carry the word @default; the code half is what counts.
    const code = line.split('///')[0].split('//')[0];
    const field = code.match(/^\s*(\w+)\s+(\w+)(\??|\[\])?\s/);
    const fallback = code.match(/@default\(([^)]*(?:\([^)]*\))?[^)]*)\)/);
    if (!field || !fallback) continue;

    const [, name, type, modifier] = field;
    const value = fallback[1].trim();

    if (APPLICATION_SIDE.test(value)) continue;

    found.push({
      table: model,
      column: name,
      type,
      optional: modifier === '?',
      value,
    });
  }

  return found;
}

/** Every default constraint SQL Server holds, as "Table.column" -> definition. */
function sqlServerDefaults() {
  const query = `
    SET NOCOUNT ON;
    SELECT OBJECT_NAME(d.parent_object_id) + '|' + c.name + '|' + d.definition
    FROM sys.default_constraints d
    JOIN sys.columns c
      ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id;`;

  const out = execFileSync(
    SQLCMD,
    ['-S', SERVER, '-d', DATABASE, '-I', '-b', '-h', '-1', '-W', '-Q', query],
    { encoding: 'utf8' });

  const held = new Map();
  for (const line of out.split(/\r?\n/)) {
    const [table, column, ...rest] = line.trim().split('|');
    if (!table || !column || rest.length === 0) continue;
    held.set(`${table}.${column}`, rest.join('|'));
  }
  return held;
}

/** Which tables SQL Server actually has, so an absent one is not read as a gap. */
function sqlServerTables() {
  const out = execFileSync(
    SQLCMD,
    ['-S', SERVER, '-d', DATABASE, '-I', '-b', '-h', '-1', '-W',
     '-Q', "SET NOCOUNT ON; SELECT name FROM sys.tables;"],
    { encoding: 'utf8' });

  return new Set(out.split(/\r?\n/).map((l) => l.trim()).filter(Boolean));
}

const wanted = prismaDefaults(readFileSync(PRISMA, 'utf8'));
const held = sqlServerDefaults();
const tables = sqlServerTables();

const missing = [];
const skipped = [];

for (const column of wanted) {
  if (!tables.has(column.table)) { skipped.push(column); continue; }
  if (held.has(`${column.table}.${column.column}`)) continue;
  missing.push(column);
}

console.log(`${wanted.length} database defaults in the Prisma schema.`);
console.log(`${held.size} default constraints on SQL Server.`);

if (skipped.length > 0) {
  console.log(`\n${skipped.length} on tables SQL Server does not have (not a gap in defaults):`);
  for (const c of skipped) console.log(`  ${c.table}.${c.column}`);
}

if (missing.length === 0) {
  console.log('\nNothing missing.');
} else {
  // NOT NULL first: those are the ones that fail an INSERT rather than merely
  // storing a null where PostgreSQL would have stored a value.
  missing.sort((a, b) => Number(a.optional) - Number(b.optional));

  console.log(`\n${missing.length} missing on SQL Server:\n`);
  for (const c of missing) {
    const severity = c.optional ? 'writes NULL ' : 'INSERT FAILS';
    console.log(`  ${severity}  ${c.table}.${c.column}  ${c.type}  @default(${c.value})`);
  }
}
