// <auto-generated />
using System;
using AutoPartsHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoPartsHub.Api.Data.Migrations
{
    [DbContext(typeof(AutoPartsContext))]
    [Migration("20260910101517_InitialSqlServerSchema")]
    partial class InitialSqlServerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("clientId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("Cart_pkey");

                    b.HasIndex(new[] { "ClientId" }, "Cart_clientId_key")
                        .IsUnique();

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.CartItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("addedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("cartId");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("productId");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("CartItem_pkey");

                    b.HasIndex(new[] { "CartId", "ProductId" }, "CartItem_cartId_productId_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ProductId" }, "CartItem_productId_idx");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("categoryId");

                    b.Property<string>("City")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrencyId")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("currencyId");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("float")
                        .HasColumnName("discountPercent");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("emailConfirmedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'RETAIL'");

                    b.Property<string>("SalesManagerId")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("salesManagerId");

                    b.Property<string>("SupplierId")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("supplierId");

                    b.HasKey("Id")
                        .HasName("Client_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "CurrencyId" }, "Client_currencyId_idx");

                    b.HasIndex(new[] { "Email" }, "Client_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "SalesManagerId" }, "Client_salesManagerId_idx");

                    b.HasIndex(new[] { "SupplierId" }, "Client_supplierId_idx");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.ClientCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<double>("MarkupPercent")
                        .HasColumnType("float")
                        .HasColumnName("markupPercent");

                    b.Property<double>("MinOrderAmount")
                        .HasColumnType("float")
                        .HasColumnName("minOrderAmount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit")
                        .HasColumnName("requiresApproval");

                    b.Property<int>("ShelfLifeDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("shelfLifeDays");

                    b.HasKey("Id")
                        .HasName("ClientCategory_pkey");

                    b.ToTable("ClientCategory", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Currency", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("code");

                    b.Property<bool>("IsBase")
                        .HasColumnType("bit")
                        .HasColumnName("isBase");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<double>("Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0)
                        .HasColumnName("rate");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("Currency_pkey");

                    b.HasIndex(new[] { "Code" }, "Currency_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "IsBase" }, "Currency_single_base")
                        .IsUnique()
                        .HasFilter("([isBase] = 1)");

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Fitment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("note");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("productId");

                    b.Property<string>("VariantId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("variantId");

                    b.HasKey("Id")
                        .HasName("Fitment_pkey");

                    b.HasIndex(new[] { "ProductId", "VariantId" }, "Fitment_productId_variantId_key")
                        .IsUnique();

                    b.HasIndex(new[] { "VariantId" }, "Fitment_variantId_idx");

                    b.ToTable("Fitment", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Interchange", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<bool>("ExactMatch")
                        .HasColumnType("bit")
                        .HasColumnName("exactMatch");

                    b.Property<bool>("IsOem")
                        .HasColumnType("bit")
                        .HasColumnName("isOEM");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("sourceId");

                    b.Property<string>("TargetManufacturer")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("targetManufacturer");

                    b.Property<string>("TargetPartNo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("targetPartNo");

                    b.HasKey("Id")
                        .HasName("Interchange_pkey");

                    b.HasIndex("SourceId");

                    b.HasIndex(new[] { "IsOem" }, "Interchange_isOEM_idx");

                    b.ToTable("Interchange", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Manufacturer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<bool>("IsOem")
                        .HasColumnType("bit")
                        .HasColumnName("isOEM");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("Manufacturer_pkey");

                    b.HasIndex(new[] { "Name" }, "Manufacturer_name_key")
                        .IsUnique();

                    b.ToTable("Manufacturer", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.MarkupRule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndsAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("endsAt");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("label");

                    b.Property<double?>("MinAmount")
                        .HasColumnType("float")
                        .HasColumnName("minAmount");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<double?>("PurchasePriceFrom")
                        .HasColumnType("float")
                        .HasColumnName("purchasePriceFrom");

                    b.Property<double?>("PurchasePriceTo")
                        .HasColumnType("float")
                        .HasColumnName("purchasePriceTo");

                    b.Property<int>("Specificity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("specificity");

                    b.Property<DateTime?>("StartsAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("startsAt");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'PERCENT'");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("MarkupRule_pkey");

                    b.ToTable("MarkupRule", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.MarkupRuleCondition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("dimension");

                    b.Property<bool>("Negated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("negated");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("ruleId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("MarkupRuleCondition_pkey");

                    b.HasIndex("RuleId", "Dimension", "Value")
                        .IsUnique()
                        .HasDatabaseName("MarkupRuleCondition_ruleId_dimension_value_key");

                    b.ToTable("MarkupRuleCondition", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("body");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("clientId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Link")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("link");

                    b.Property<DateTime?>("ReadAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("readAt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'system'");

                    b.HasKey("Id")
                        .HasName("Notification_pkey");

                    b.HasIndex(new[] { "ClientId", "ReadAt" }, "Notification_clientId_readAt_idx");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("clientId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("currencyCode")
                        .HasDefaultValueSql("'EUR'");

                    b.Property<double>("CurrencyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0)
                        .HasColumnName("currencyRate");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'order_is_sent'");

                    b.HasKey("Id")
                        .HasName("Order_pkey");

                    b.HasIndex("ClientId");

                    b.HasIndex(new[] { "Reference" }, "Order_reference_key")
                        .IsUnique();

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("orderId");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("productId");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float")
                        .HasColumnName("unitPrice");

                    b.HasKey("Id")
                        .HasName("OrderItem_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.OrderItemAllocation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("OrderItemId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("orderItemId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("warehouseId");

                    b.HasKey("Id")
                        .HasName("OrderItemAllocation_pkey");

                    b.HasIndex(new[] { "OrderItemId", "WarehouseId" }, "OrderItemAllocation_orderItemId_warehouseId_key")
                        .IsUnique();

                    b.HasIndex(new[] { "WarehouseId" }, "OrderItemAllocation_warehouseId_idx");

                    b.ToTable("OrderItemAllocation", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.PriceList", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<string>("SourceName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("sourceName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("PriceList_pkey");

                    b.HasIndex(new[] { "Active" }, "PriceList_one_active")
                        .IsUnique()
                        .HasFilter("([active] = 1)");

                    b.ToTable("PriceList", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.PriceListItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<string>("PriceListId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("priceListId");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("productId");

                    b.Property<string>("SourceCurrency")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("sourceCurrency");

                    b.Property<double?>("SourcePrice")
                        .HasColumnType("float")
                        .HasColumnName("sourcePrice");

                    b.HasKey("Id")
                        .HasName("PriceListItem_pkey");

                    b.HasIndex(new[] { "PriceListId", "ProductId" }, "PriceListItem_priceListId_productId_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ProductId" }, "PriceListItem_productId_idx");

                    b.ToTable("PriceListItem", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<double>("BasePrice")
                        .HasColumnType("float")
                        .HasColumnName("basePrice");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'EUR'");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("description");

                    b.Property<string>("ManufacturerId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("manufacturerId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("partNumber");

                    b.Property<int>("StockDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("stockDays");

                    b.Property<string>("SupplierId")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("supplierId");

                    b.Property<int?>("TecDocId")
                        .HasColumnType("int")
                        .HasColumnName("tecDocId");

                    b.Property<string>("VehicleSystemId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("vehicleSystemId");

                    b.HasKey("Id")
                        .HasName("Product_pkey");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VehicleSystemId");

                    b.HasIndex(new[] { "PartNumber" }, "Product_partNumber_key")
                        .IsUnique();

                    b.HasIndex(new[] { "SupplierId" }, "Product_supplierId_idx");

                    b.HasIndex(new[] { "TecDocId" }, "Product_tecDocId_key")
                        .IsUnique()
                        .HasFilter("[tecDocId] IS NOT NULL");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.ProductImage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("Alt")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("alt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("productId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sortOrder");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("ProductImage_pkey");

                    b.HasIndex(new[] { "ProductId", "SortOrder" }, "ProductImage_productId_sortOrder_idx");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.RetailOutlet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("phone");

                    b.Property<string>("WarehouseId")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("warehouseId");

                    b.HasKey("Id")
                        .HasName("RetailOutlet_pkey");

                    b.HasIndex(new[] { "Code" }, "RetailOutlet_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "WarehouseId" }, "RetailOutlet_warehouseId_idx");

                    b.ToTable("RetailOutlet", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.StockLevel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("BinLocation")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("binLocation");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("productId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("Reserved")
                        .HasColumnType("int")
                        .HasColumnName("reserved");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updatedAt");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("warehouseId");

                    b.HasKey("Id")
                        .HasName("StockLevel_pkey");

                    b.HasIndex(new[] { "ProductId", "WarehouseId" }, "StockLevel_productId_warehouseId_key")
                        .IsUnique();

                    b.HasIndex(new[] { "WarehouseId" }, "StockLevel_warehouseId_idx");

                    b.ToTable("StockLevel", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<bool?>("AcceptsReturns")
                        .HasColumnType("bit")
                        .HasColumnName("acceptsReturns");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("approvedAt");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("country");

                    b.Property<int?>("DefaultStockDays")
                        .HasColumnType("int")
                        .HasColumnName("defaultStockDays");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("description");

                    b.Property<int?>("GuaranteeMonths")
                        .HasColumnType("int")
                        .HasColumnName("guaranteeMonths");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<string>("PurchaseCurrencyId")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("purchaseCurrencyId");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<string>("Reliability")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("reliability")
                        .HasDefaultValueSql("'standard'");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("Supplier_pkey");

                    b.HasIndex(new[] { "AcceptsReturns" }, "Supplier_acceptsReturns_idx");

                    b.HasIndex(new[] { "Code" }, "Supplier_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Country" }, "Supplier_country_idx");

                    b.HasIndex(new[] { "PurchaseCurrencyId" }, "Supplier_purchaseCurrencyId_idx");

                    b.HasIndex(new[] { "Rating" }, "Supplier_rating_idx");

                    b.HasIndex(new[] { "Slug" }, "Supplier_slug_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Active" }, "Supplier_waiting_idx")
                        .HasFilter("([active] = 0)");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VehicleMake", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<int?>("TecDocId")
                        .HasColumnType("int")
                        .HasColumnName("tecDocId");

                    b.PrimitiveCollection<string>("WmiCodes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("wmiCodes");

                    b.HasKey("Id")
                        .HasName("VehicleMake_pkey");

                    b.HasIndex(new[] { "Name" }, "VehicleMake_name_key")
                        .IsUnique();

                    b.HasIndex(new[] { "TecDocId" }, "VehicleMake_tecDocId_key")
                        .IsUnique()
                        .HasFilter("[tecDocId] IS NOT NULL");

                    b.ToTable("VehicleMake", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VehicleModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("MakeId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("makeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<int?>("TecDocId")
                        .HasColumnType("int")
                        .HasColumnName("tecDocId");

                    b.Property<int>("YearFrom")
                        .HasColumnType("int")
                        .HasColumnName("yearFrom");

                    b.Property<int?>("YearTo")
                        .HasColumnType("int")
                        .HasColumnName("yearTo");

                    b.HasKey("Id")
                        .HasName("VehicleModel_pkey");

                    b.HasIndex(new[] { "MakeId", "Name" }, "VehicleModel_makeId_name_key")
                        .IsUnique();

                    b.HasIndex(new[] { "TecDocId" }, "VehicleModel_tecDocId_key")
                        .IsUnique()
                        .HasFilter("[tecDocId] IS NOT NULL");

                    b.ToTable("VehicleModel", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VehicleSystem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("VehicleSystem_pkey");

                    b.HasIndex(new[] { "Slug" }, "VehicleSystem_slug_key")
                        .IsUnique();

                    b.ToTable("VehicleSystem", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VehicleVariant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("EngineCode")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("engineCode");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("fuel")
                        .HasDefaultValueSql("'diesel'");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("modelId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<int?>("PowerKw")
                        .HasColumnType("int")
                        .HasColumnName("powerKw");

                    b.Property<int?>("TecDocId")
                        .HasColumnType("int")
                        .HasColumnName("tecDocId");

                    b.Property<int>("YearFrom")
                        .HasColumnType("int")
                        .HasColumnName("yearFrom");

                    b.Property<int?>("YearTo")
                        .HasColumnType("int")
                        .HasColumnName("yearTo");

                    b.HasKey("Id")
                        .HasName("VehicleVariant_pkey");

                    b.HasIndex(new[] { "ModelId", "Name" }, "VehicleVariant_modelId_name_key")
                        .IsUnique();

                    b.HasIndex(new[] { "TecDocId" }, "VehicleVariant_tecDocId_key")
                        .IsUnique()
                        .HasFilter("[tecDocId] IS NOT NULL");

                    b.ToTable("VehicleVariant", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VerificationToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("clientId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("expiresAt");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("tokenHash");

                    b.Property<DateTime?>("UsedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("usedAt");

                    b.HasKey("Id")
                        .HasName("VerificationToken_pkey");

                    b.HasIndex(new[] { "ClientId", "Purpose" }, "VerificationToken_clientId_purpose_idx");

                    b.HasIndex(new[] { "TokenHash" }, "VerificationToken_tokenHash_key")
                        .IsUnique();

                    b.ToTable("VerificationToken", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Warehouse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.HasKey("Id")
                        .HasName("Warehouse_pkey");

                    b.HasIndex(new[] { "Code" }, "Warehouse_code_key")
                        .IsUnique();

                    b.ToTable("Warehouse", (string)null);
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Cart", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Client", "Client")
                        .WithOne("Cart")
                        .HasForeignKey("AutoPartsHub.Api.Data.Entities.Cart", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Cart_clientId_fkey");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.CartItem", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CartItem_cartId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CartItem_productId_fkey");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Client", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.ClientCategory", "Category")
                        .WithMany("Clients")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Client_categoryId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.Currency", "Currency")
                        .WithMany("Clients")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Client_currencyId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.Client", "SalesManager")
                        .WithMany("InverseSalesManager")
                        .HasForeignKey("SalesManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("Client_salesManagerId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.Supplier", "Supplier")
                        .WithMany("Clients")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Client_supplierId_fkey");

                    b.Navigation("Category");

                    b.Navigation("Currency");

                    b.Navigation("SalesManager");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Fitment", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Product", "Product")
                        .WithMany("Fitments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Fitment_productId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.VehicleVariant", "Variant")
                        .WithMany("Fitments")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Fitment_variantId_fkey");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Interchange", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Product", "Source")
                        .WithMany("Interchanges")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Interchange_sourceId_fkey");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.MarkupRuleCondition", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.MarkupRule", "Rule")
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MarkupRuleCondition_ruleId_fkey");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Notification", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Client", "Client")
                        .WithMany("Notifications")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Notification_clientId_fkey");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Order", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Order_clientId_fkey");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("OrderItem_orderId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("OrderItem_productId_fkey");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.OrderItemAllocation", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.OrderItem", "OrderItem")
                        .WithMany("OrderItemAllocations")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("OrderItemAllocation_orderItemId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.Warehouse", "Warehouse")
                        .WithMany("OrderItemAllocations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("OrderItemAllocation_warehouseId_fkey");

                    b.Navigation("OrderItem");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.PriceListItem", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.PriceList", "PriceList")
                        .WithMany("PriceListItems")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PriceListItem_priceListId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.Product", "Product")
                        .WithMany("PriceListItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PriceListItem_productId_fkey");

                    b.Navigation("PriceList");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Product", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Product_manufacturerId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Product_supplierId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.VehicleSystem", "VehicleSystem")
                        .WithMany("Products")
                        .HasForeignKey("VehicleSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Product_vehicleSystemId_fkey");

                    b.Navigation("Manufacturer");

                    b.Navigation("Supplier");

                    b.Navigation("VehicleSystem");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ProductImage_productId_fkey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.RetailOutlet", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Warehouse", "Warehouse")
                        .WithMany("RetailOutlets")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("RetailOutlet_warehouseId_fkey");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.StockLevel", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Product", "Product")
                        .WithMany("StockLevels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("StockLevel_productId_fkey");

                    b.HasOne("AutoPartsHub.Api.Data.Entities.Warehouse", "Warehouse")
                        .WithMany("StockLevels")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("StockLevel_warehouseId_fkey");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Supplier", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Currency", "PurchaseCurrency")
                        .WithMany("Suppliers")
                        .HasForeignKey("PurchaseCurrencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Supplier_purchaseCurrencyId_fkey");

                    b.Navigation("PurchaseCurrency");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VehicleModel", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.VehicleMake", "Make")
                        .WithMany("VehicleModels")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("VehicleModel_makeId_fkey");

                    b.Navigation("Make");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VehicleVariant", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.VehicleModel", "Model")
                        .WithMany("VehicleVariants")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("VehicleVariant_modelId_fkey");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VerificationToken", b =>
                {
                    b.HasOne("AutoPartsHub.Api.Data.Entities.Client", "Client")
                        .WithMany("VerificationTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("VerificationToken_clientId_fkey");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Client", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("InverseSalesManager");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("VerificationTokens");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.ClientCategory", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Currency", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.MarkupRule", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.OrderItem", b =>
                {
                    b.Navigation("OrderItemAllocations");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.PriceList", b =>
                {
                    b.Navigation("PriceListItems");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Fitments");

                    b.Navigation("Interchanges");

                    b.Navigation("OrderItems");

                    b.Navigation("PriceListItems");

                    b.Navigation("ProductImages");

                    b.Navigation("StockLevels");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Supplier", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VehicleMake", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VehicleModel", b =>
                {
                    b.Navigation("VehicleVariants");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VehicleSystem", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.VehicleVariant", b =>
                {
                    b.Navigation("Fitments");
                });

            modelBuilder.Entity("AutoPartsHub.Api.Data.Entities.Warehouse", b =>
                {
                    b.Navigation("OrderItemAllocations");

                    b.Navigation("RetailOutlets");

                    b.Navigation("StockLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
